name: Publish common library

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN}}
        run: ./gradlew publish
